### ISSUE TITLE
node-express-server-rest-api: body-parser

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/blog_robinwieruch_content#106]
> Hi Robin,
> 
> (I know you probably already know this so it's more for anyone else following this tutorial)
> 
> I think we don't need the body-parser package any longer because Express now comes built in with the functions that body-parser provided. Now we can simply use app.use(express.json()); and app.use(express.urlencoded({ extended: true })); instead! :)

See https://www.robinwieruch.de/node-express-server-rest-api/#comment-4467266016

**Comment by briantomillo** [comment]
I updated to reflect the changes and will open a pull request.
