### ISSUE TITLE
possible non-attributed non-licensed image

### ISSUE THREAD

**Issue by knowuh** [rwieruch/blog_robinwieruch_content#131]
Hello,

I am writing to ask about this image:

https://github.com/rwieruch/blog_robinwieruch_content/blob/master/blog/redux-javascript/images/banner.jpg

Can you tell me how you came by the image, and what license you are redistributing it under?  Are you the copyright holder?

**Comment by rwieruch** [comment]
I am not the copyright holder, but the image is free for use from over here https://www.pexels.com/photo/woman-wearing-red-and-black-feather-hat-923345/
