### ISSUE TITLE
link broken on https://www.robinwieruch.de/the-road-to-graphql-book

### ISSUE THREAD

**Issue by jonolo6** [rwieruch/blog_robinwieruch_content#165]
I'm on mac/chrome (81.0.4044.138 (Official Build) (64-bit)) and Catalina (10.15.4).

![image](https://user-images.githubusercontent.com/3819396/82229292-a07fc800-9900-11ea-88d8-321844faef59.png)

**Comment by rwieruch** [comment]
Thanks for reporting. I have this issue somewhere else already on my todo list! 👍
