### ISSUE TITLE
Typo.

### ISSUE THREAD

**Issue by dephraiim** [rwieruch/blog_robinwieruch_content#177]
How to set up an advanced Webpack application 

index.md: line 19 last sentence
#### Make sure to give it a **start** if you like it.

I'm I missing something or it is a typo?

**Comment by rwieruch** [comment]
Not the best sentence :D I removed it https://github.com/rwieruch/blog_robinwieruch_content/commit/f44cf71bf7f937223afe55d07fdcac25cfc09ae5
