### ISSUE TITLE
Typo. webpack-advanced-setup-tutorial

### ISSUE THREAD

**Issue by dephraiim** [rwieruch/blog_robinwieruch_content#179]
```
const HtmlWebpackPlugin = require('html-webpack-plugin')
 
module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Hello Webpack bundled JavaScript Project',
      template: './src/index.html'
    })
  ],
  ...
};
```

Isn't the template supposed to be `template: './dist/index.html'` because our html file is in the `dist` folder.

**Comment by rwieruch** [comment]
The *index.html* is in the *src/* folder.

![Jul-14-2020 10-00-29](https://user-images.githubusercontent.com/2479967/87400544-4118fe00-c5b9-11ea-91f3-48d170e1ada7.gif)

On `npm run build`, the *index.html* is copied into the *dist/* folder.

On every `npm run build`the *dist/* folder gets removed.

That's the whole flow :)
