### ISSUE TITLE
Changes in Webpack make the suggested configurations throw an error (Adding Babel)

### ISSUE THREAD

**Issue by diego-caceres** [rwieruch/blog_robinwieruch_content#3]
When we are adding Babel to the project, the tutorial suggests to add the following configuration to 'webpack.config.js' : 
`module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'react-hot!babel'
    }]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },`
But if you try to start the project you get an error. The problem is that WebPack's new version doesn't support providing empty extensions, and also the '-loader' part of libraries cannot be skipped. 

The working configuration for me ended up like this: 
`module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'react-hot-loader!babel-loader'
    }]
  },
  resolve: {
    extensions: ['.js', '.jsx']
  },`

**Comment by rwieruch** [comment]
@diego-caceres thanks for your report. I will change it 👍 Can you confirm that `extensions: ['*', '.js', '.jsx']` works for you as well?

**Comment by rwieruch** [comment]
https://github.com/rwieruch/blog_robinwieruch_content/commit/96aa7c68dd1300c7fc7745f36a95aaeef3d79897

**Comment by diego-caceres** [comment]
@rwieruch sorry for the late response, but yes, it effectively works as well 👍
