### ISSUE TITLE
Minor inconvenience: routes used in SignUp.js before being imported.

### ISSUE THREAD

**Issue by guosim** [rwieruch/blog_robinwieruch_content#33]
routes is not defined before being used in `<Link to={routes.SIGN_UP}>Sign Up</Link>`, making the code unable to compile while working through SignUpForm. Not sure if better to just leave the SignUpLink out first or just import routes at the start.

Edit: Whoops, this is for "A Complete Firebase in React Authentication Tutorial".

**Comment by rwieruch** [comment]
Thank you! You mean this https://github.com/rwieruch/blog_robinwieruch_content/commit/df04b987a245ec248988226a7f6bd2d0b85cf77d would fix it when the SignUp.js is touched the first time?

**Comment by guosim** [comment]
Yep, that would fix it!

**Comment by rwieruch** [comment]
Thanks for mentioning it!
