### ISSUE TITLE
react-hooks-fetch-data: cleaner API

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/blog_robinwieruch_content#89]
See https://www.robinwieruch.de/react-hooks-fetch-data/#comment-4374330989

- [ ] Blog post to be changed: https://github.com/rwieruch/blog_robinwieruch_content/blob/master/react-hooks-fetch-data.md

- [x] Code to be changed: https://github.com/the-road-to-learn-react/react-hooks-introduction/blob/master/src/useDataApiHook-example/index.js

**Comment by John-Spraul** [comment]
Hi Robin! I wanted to contribute to your work in some way. I find what you do to be helpful and inspiring, and I would love an opportunity to work with / learn from you.

I hope those PRs help 🙌

**Comment by rwieruch** [comment]
Thank you so much John! I merged and committed my own changes. Your contribution gave me the perfect input to get this improved :)
